services:
  postgres:
    image: postgres:16
    container_name: trackmyrun_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trackmyrun
    ports:
      - "5433:5432"